service:
  name: api-gateway-websocket-sandbox
  stage: dev
  websocketApiRouteSelectionExpression: $request.body.action

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-websockets-plugin

functions:
  connectionHandler:
    handler: src/handler.main
    events:
      - websocket:
          routeKey: $connect
      - websocket:
          routeKey: $disconnect
  defaultHandler:
    events:
      - websocket:
          routeKey: $default
  actionHandler:
    events:
      - websocket:
          routeKey: myAction
